version: '3.8'

services:
  # Service 1: Aplikasi Node.js
  app:
    build: ./app
    container_name: libratech_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql_db
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=libratech_db
    depends_on:
      - mysql_db

  # Service 2: Database MySQL
  mysql_db:
    image: mysql:5.7
    container_name: libratech_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=libratech_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    volumes:
      # PENTING: Agar data tidak hilang (Persistent) [cite: 128, 200]
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Service 3: Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: libratech_nginx
    restart: always
    ports:
      # Akses publik lewat port 2583 sesuai aturan [cite: 194]
      - "2583:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data: